# Generated by Django 3.2.9 on 2021-11-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('question', models.CharField(max_length=225)),
                ('true_answer', models.CharField(max_length=225)),
                ('false_answer', models.CharField(max_length=225)),
                ('false_answer2', models.CharField(max_length=225)),
                ('false_answer3', models.CharField(max_length=225)),
            ],
            options={
                'db_table': 'question',
            },
        ),
    ]
